# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  run-npm-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
        
      - name: Extract packageJSON
        id: set_var
        run: |
          content=`cat package.json`
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          echo "::set-output name=packageJson::$content"
          
      - name: Update package.json version
        run: |
          mv package.json package.tmp.json
          cat package.tmp.json | jq '.version = "${{format('{0}-{1}', fromJson(steps.set_var.outputs.packageJson).contextPath, github.sha)}}"' > package.json
          rm package.tmp.json
  
      - name: Deployment
        run: |
          npm install
          npm run build
          npm run deploy -- -u ${{ vars.ENVIRONMENT_URL }} -U ${{ vars.USER_NAME }} -P ${{ vars.PASSWORD }} --app.contextPath="${{format('{0}-{1}', fromJson(steps.set_var.outputs.packageJson).contextPath, steps.extract_branch.outputs.branch) }}"
